apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
      - name: mern-client
        image: minabf/mern-client:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:5000"
          