apiVersion: v1
kind: Service
metadata:
  name: mern-server-service
spec:
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 # Port sur lequel le conteneur écoute à l'intérieur du pod
  type: LoadBalancer